// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChaTFDF2ZiGKsl4igEeTva1qw78XiHDXU',
    appId: '1:829946963132:web:5f524bff783c3ab0e65cb9',
    messagingSenderId: '829946963132',
    projectId: 'phoneauth-d4171',
    authDomain: 'phoneauth-d4171.firebaseapp.com',
    storageBucket: 'phoneauth-d4171.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1K1QVSC0DlpoN5V6huBPHFL_4gPcabo4',
    appId: '1:829946963132:android:b2a3d79615936dcae65cb9',
    messagingSenderId: '829946963132',
    projectId: 'phoneauth-d4171',
    storageBucket: 'phoneauth-d4171.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMzpcAMjzFtdEOh1LUgQtzIqAv5sx_jPQ',
    appId: '1:829946963132:ios:210dc4f4d3c88714e65cb9',
    messagingSenderId: '829946963132',
    projectId: 'phoneauth-d4171',
    storageBucket: 'phoneauth-d4171.appspot.com',
    iosBundleId: 'com.example.phoneauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMzpcAMjzFtdEOh1LUgQtzIqAv5sx_jPQ',
    appId: '1:829946963132:ios:2668b76579827420e65cb9',
    messagingSenderId: '829946963132',
    projectId: 'phoneauth-d4171',
    storageBucket: 'phoneauth-d4171.appspot.com',
    iosBundleId: 'com.example.phoneauth.RunnerTests',
  );
}
